name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Force-install your exact pins so imports never fail
      - name: Force-install core runtime deps
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install \
            pandas==1.5.3 \
            numpy==1.25.2 \
            scikit-learn==1.2.2 \
            pycaret==3.2.0 \
            streamlit==1.33.0 \
            mlflow==2.12.1 \
            omegaconf==2.3.0 \
            hydra-core==1.3.2 \
            catboost==1.2.5 \
            lightgbm==4.6.0 \
            pyyaml==6.0.2
          echo "---- pip freeze (tail) ----"
          python -m pip freeze | tail -n +1

      - name: Import checks
        run: |
          python - <<'PY'
          import pandas, numpy, sklearn, pycaret, streamlit, mlflow, omegaconf, hydra
          print("Imports OK")
          PY

      - name: Lint (basic)
        run: |
          python -m pip install pyflakes
          pyflakes streamlit_app.py || exit 0

